[pytest]
DJANGO_SETTINGS_MODULE = portfolio_management.settings
python_files = tests.py test_*.py *_tests.py
markers =
    unit: marks tests as unit tests
    integration: marks tests as integration tests
    performance: marks tests as performance tests
    regression: marks tests as regression tests
    edge_case: marks tests as edge case tests
    production: marks tests as production snapshot tests
    nav: marks tests related to NAV calculations
    fx: marks tests related to FX calculations
    buy_in_price: marks tests related to buy-in price calculations
    gain_loss: marks tests related to gain/loss calculations
