"""Utility functions for managing securities/assets data.

This module provides functions to retrieve, filter, and format
securities data for display in tables and API responses.
"""

import logging
from datetime import date, datetime
from decimal import ROUND_HALF_UP, Decimal

from django.db.models import Prefetch, Q
from django.shortcuts import get_object_or_404

from common.models import Assets, Transactions
from constants import ASSET_TYPE_CRYPTO, TRANSACTION_TYPE_CRYPTO_REWARD
from core.portfolio_utils import IRR
from services.bonds import calculate_bond_ytm, get_current_aci, get_current_notional
from services.capital import get_capital_distribution
from services.fx import get_rate as fx_get_rate
from services.pricing import calculate_value_at_date, price_at_date
from services.positions import investment_date, position
from services.realized import (
    calculate_buy_in_price,
    realized_gain_loss,
    unrealized_gain_loss,
)

from .formatting_utils import format_table_data, format_value
from .pagination_utils import paginate_table
from .sorting_utils import sort_entries

logger = logging.getLogger(__name__)


# =============================================================================
# Securities API Functions
# =============================================================================


def get_crypto_reward_totals(
    security: Assets,
    user,
    effective_date: date,
    account_ids: list = None,
    currency: str = "USD",
) -> tuple[Decimal, Decimal]:
    """Return crypto reward totals in native units and selected fiat currency."""
    reward_transactions = security.transactions.filter(
        type=TRANSACTION_TYPE_CRYPTO_REWARD,
        investor=user,
        date__date__lte=effective_date,
    )
    if account_ids:
        reward_transactions = reward_transactions.filter(account_id__in=account_ids)

    native_quantity = Decimal("0")
    fiat_value = Decimal("0")

    for transaction in reward_transactions:
        native_quantity += transaction.quantity or Decimal("0")
        reward_value = transaction.reward_value()
        if transaction.currency != currency:
            fx_rate = fx_get_rate(transaction.currency, currency, transaction.date)["FX"]
            if not fx_rate:
                continue
            reward_value *= Decimal(fx_rate)
        fiat_value += reward_value

    return native_quantity, fiat_value.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def get_securities_table_api(request):
    """Retrieve and format securities table data for API response.

    Args:
        request: The HTTP request object containing user context and parameters.

    Returns:
        dict: Dictionary containing formatted securities data, totals, and
            pagination information with keys: securities, totals, total_items,
            current_page, total_pages.
    """
    data = request.data
    page = int(data.get("page"))
    items_per_page = int(data.get("itemsPerPage"))
    search = data.get("search", "")
    sort_by = data.get("sortBy", {})

    user = request.user
    # Use JWT middleware instead of session
    effective_current_date_str = getattr(
        request, "effective_current_date", datetime.now().date().isoformat()
    )
    effective_current_date = datetime.strptime(effective_current_date_str, "%Y-%m-%d").date()
    number_of_digits = user.digits

    securities_data = _filter_securities(user, search)
    securities_data = _get_securities_data(user, securities_data, effective_current_date)
    securities_data = sort_entries(securities_data, sort_by)
    paginated_securities, pagination_data = paginate_table(securities_data, page, items_per_page)
    formatted_securities = [
        {k: format_value(v, k, position["currency"], number_of_digits) for k, v in position.items()}
        for position in paginated_securities.object_list
    ]

    return {
        "securities": formatted_securities,
        "total_items": pagination_data["total_items"],
        "current_page": pagination_data["current_page"],
        "total_pages": pagination_data["total_pages"],
    }


def _filter_securities(user, search):
    """Filter securities with optimized query using prefetch_related."""
    securities = (
        Assets.objects.filter(investors__id=user.id)
        # Use actual OneToOne related names generated by InstrumentMetadata: %(class)s_metadata
        # e.g. bondmetadata_metadata, optionmetadata_metadata, futuremetadata_metadata
        .select_related(
            "bondmetadata_metadata",
            "optionmetadata_metadata",
            "futuremetadata_metadata",
        ).prefetch_related(
            Prefetch(
                "transactions",
                queryset=Transactions.objects.filter(investor=user)
                .select_related("account")
                .order_by("date"),
            ),
            "prices",
            "coupon_schedule",
            "notional_history",
        )
    )

    if search:
        search_query = (
            Q(name__icontains=search) | Q(ISIN__icontains=search) | Q(currency__icontains=search)
        )
        securities = securities.filter(search_query)

    return securities


def _get_securities_data(user, securities, effective_current_date):
    securities_data = []
    for security in securities:
        security_data = {
            "id": security.id,
            "type": security.type,
            "ISIN": security.ISIN,
            "name": security.name,
            "first_investment": investment_date(security, user) or "None",
            "currency": security.currency,
            "open_position": position(security, effective_current_date, user),
            "current_value": calculate_value_at_date(
                security, effective_current_date, user, security.currency
            ),
            "realized": realized_gain_loss(security, effective_current_date, user)["all_time"][
                "total"
            ],
            "unrealized": unrealized_gain_loss(security, effective_current_date, user)["total"],
            "capital_distribution": get_capital_distribution(
                security, effective_current_date, user
            ),
            "irr": IRR(user.id, effective_current_date, security.currency, asset_id=security.id),
        }

        securities_data.append(security_data)
    return securities_data


def get_security_detail(request, security_id, account_id=None):
    """Retrieve detailed information for a specific security.

    Args:
        request: The HTTP request object.
        security_id: The ID of the security to retrieve details for.
        account_id: Optional account ID to filter calculations by.

    Returns:
        dict: Dictionary containing detailed security information.
    """
    user = request.user
    # Use JWT middleware instead of session
    effective_current_date_str = getattr(
        request, "effective_current_date", datetime.now().date().isoformat()
    )
    effective_current_date = datetime.strptime(effective_current_date_str, "%Y-%m-%d").date()
    number_of_digits = user.digits

    security = get_object_or_404(Assets, id=security_id, investors__id=user.id)

    # Resolve account_ids filter
    account_ids = [account_id] if account_id else None

    # Cache price lookup to avoid duplicate queries
    current_price_obj = price_at_date(security, effective_current_date)
    current_price = current_price_obj.price if current_price_obj else None

    # Base security data
    security_data = {
        "id": security.id,
        "instrument_type": security.type,
        "ISIN": security.ISIN,
        "name": security.name,
        "first_investment": investment_date(security, user, account_ids=account_ids) or "None",
        "currency": security.currency,
        "open_position": position(
            security, effective_current_date, user, account_ids=account_ids
        ),
        "current_value": calculate_value_at_date(
            security, effective_current_date, user, security.currency, account_ids=account_ids
        ),
        "realized": realized_gain_loss(
            security, effective_current_date, user, account_ids=account_ids
        )["all_time"]["total"],
        "unrealized": unrealized_gain_loss(
            security, effective_current_date, user, account_ids=account_ids
        )["total"],
        "capital_distribution": get_capital_distribution(
            security, effective_current_date, user, account_ids=account_ids
        ),
        "irr": IRR(
            user.id,
            effective_current_date,
            security.currency,
            asset_id=security.id,
            account_ids=account_ids,
        ),
        "data_source": security.data_source,
        "update_link": security.update_link,
        "yahoo_symbol": security.yahoo_symbol,
        "comment": security.comment,
        # Note: current_aci moved to bond_data below
        # Add buy-in price
        "buy_in_price": calculate_buy_in_price(
            security, effective_current_date, user, security.currency, account_ids=account_ids
        ),
        # Add current price (using cached value)
        "current_price": current_price,
    }

    # Add bond-specific data
    if security.is_bond and security.bond_metadata:
        bond_meta = security.bond_metadata

        # Get current ACI per bond (fetch once to avoid duplicate MICEX API calls)
        aci_data = get_current_aci(
            bond_meta, effective_current_date, currency=security.currency, user=user
        )

        # Calculate total ACI for position using the already-fetched aci_data
        # This avoids calling get_current_aci() twice and duplicating MICEX API calls
        if aci_data:
            position_qty = position(
                security, effective_current_date, user, account_ids=account_ids
            )
            total_aci = (
                aci_data["aci_amount"] * Decimal(position_qty) if position_qty else Decimal(0)
            )

            # Subtract ACI paid in current coupon period (same logic as get_total_aci_for_position)
            current_coupon_start = aci_data.get("coupon_start")
            if current_coupon_start and position_qty:
                query_date = effective_current_date
                query_coupon_start = current_coupon_start

                aci_paid_in_period = security.transactions.filter(
                    type="Buy",
                    aci__lt=0,
                    date__date__gte=query_coupon_start,
                    date__date__lte=query_date,
                    investor=user,
                )

                if account_ids:
                    aci_paid_in_period = aci_paid_in_period.filter(account_id__in=account_ids)

                if aci_paid_in_period.exists():
                    aci_paid_total = Decimal(0)
                    for txn in aci_paid_in_period:
                        # Convert date to ensure proper comparison
                        txn_date = txn.date.date() if isinstance(txn.date, datetime) else txn.date
                        fx_rate = fx_get_rate(txn.currency, security.currency, txn_date)["FX"]
                        if fx_rate:
                            aci_paid_total += txn.aci * Decimal(fx_rate)

                    total_aci += aci_paid_total

            total_aci = round(total_aci, 2)
        else:
            total_aci = Decimal(0)

        # current_price already cached above

        # Get current notional per bond
        current_notional = get_current_notional(
            bond_meta,
            effective_current_date,
            investor=user,
            currency=bond_meta.nominal_currency or security.currency,
        )

        # Get coupon information from the latest coupon schedule entry
        latest_coupon = (
            bond_meta.asset.coupon_schedule.filter(payment_date__lte=effective_current_date)
            .order_by("-coupon_number")
            .first()
        )
        coupon_amount = (
            latest_coupon.coupon_amount if latest_coupon and latest_coupon.coupon_amount else None
        )
        coupon_currency = (
            latest_coupon.coupon_currency
            if latest_coupon
            else (bond_meta.nominal_currency or security.currency)
        )
        coupon_type = latest_coupon.coupon_type if latest_coupon else None

        # Fallback: fetch coupon schedule if not available
        if not latest_coupon and security.tbank_instrument_uid:
            logger.info(
                f"No coupon schedule found for {security.name}, attempting to fetch from API"
            )
            try:
                from asgiref.sync import async_to_sync

                from core.tinkoff_utils import fetch_and_cache_bond_coupon_schedule

                success = async_to_sync(fetch_and_cache_bond_coupon_schedule)(
                    security, user, force_refresh=False
                )

                if success:
                    # Try again after fetching
                    latest_coupon = (
                        bond_meta.asset.coupon_schedule.filter(
                            payment_date__lte=effective_current_date
                        )
                        .order_by("-coupon_number")
                        .first()
                    )
                    coupon_amount = (
                        latest_coupon.coupon_amount
                        if latest_coupon and latest_coupon.coupon_amount
                        else None
                    )
                    coupon_currency = (
                        latest_coupon.coupon_currency
                        if latest_coupon
                        else (bond_meta.nominal_currency or security.currency)
                    )
                    coupon_type = latest_coupon.coupon_type if latest_coupon else None
            except Exception as e:
                logger.error(f"Failed to fetch coupon schedule for {security.name}: {e}")

        # Fallback: fetch redemption history if not available for all bonds
        if security.tbank_instrument_uid:
            has_redemption_history = bond_meta.asset.notional_history.exists()
            if not has_redemption_history:
                logger.info(
                    f"No redemption history found for bond "
                    f"{security.name}, attempting to fetch from API"
                )
                try:
                    from asgiref.sync import async_to_sync

                    from core.tinkoff_utils import save_bond_redemption_history

                    entries_created = async_to_sync(save_bond_redemption_history)(
                        security, security.tbank_instrument_uid, user
                    )

                    if entries_created > 0:
                        logger.info(
                            f"Created {entries_created} redemption history entries for "
                            f"{security.name}"
                        )
                except Exception as e:
                    logger.error(f"Failed to fetch redemption history for {security.name}: {e}")

        # Calculate YTM for bonds using XIRR (uses shared helper function)
        ytm_decimal = calculate_bond_ytm(user, security, effective_current_date)
        ytm = float(ytm_decimal) if ytm_decimal is not None else None

        bond_data = {
            "current_notional": float(current_notional) if current_notional is not None else None,
            "notional_currency": bond_meta.nominal_currency or security.currency,
            "initial_notional": (
                float(bond_meta.initial_notional)
                if bond_meta.initial_notional is not None
                else None
            ),
            "is_amortizing": bond_meta.is_amortizing,
            "issue_date": bond_meta.issue_date.isoformat() if bond_meta.issue_date else None,
            "maturity_date": (
                bond_meta.maturity_date.isoformat() if bond_meta.maturity_date else None
            ),
            "coupon_rate": (
                float(bond_meta.coupon_rate) if bond_meta.coupon_rate is not None else None
            ),
            "coupon_frequency": bond_meta.coupon_frequency,
            "coupon_amount": (
                float(latest_coupon.coupon_amount)
                if latest_coupon and latest_coupon.coupon_amount is not None
                else None
            ),
            "coupon_currency": coupon_currency,
            "coupon_type": coupon_type,
            "current_price_pct": float(current_price) if current_price is not None else None,
            "total_aci": float(total_aci) if total_aci is not None else None,
            "bond_type": bond_meta.bond_type,
            "credit_rating": bond_meta.credit_rating,
            # Move current_aci here and add next_coupon_date
            "current_aci": aci_data,
            "next_coupon_date": (
                aci_data.get("next_payment").isoformat()
                if aci_data and aci_data.get("next_payment")
                else None
            ),
            # Add YTM calculated with XIRR
            "ytm": float(ytm) if ytm is not None else None,
        }
        security_data["bond_data"] = bond_data

    # Apply formatting to main security data only (not bond_data)
    formatted_security_data = format_table_data(
        [security_data], security.currency, number_of_digits
    )[0]

    if security.type == ASSET_TYPE_CRYPTO:
        reward_quantity, reward_value = get_crypto_reward_totals(
            security,
            user,
            effective_current_date,
            account_ids=account_ids,
            currency=getattr(user, "default_currency", security.currency),
        )
        formatted_security_data["crypto_reward_native_quantity"] = str(
            reward_quantity.quantize(Decimal("0.000000001"), rounding=ROUND_HALF_UP)
        )
        formatted_security_data["crypto_reward_fiat_value"] = str(reward_value)

    return formatted_security_data


def get_security_transactions(request, security_id):
    """Retrieve transactions for a specific security.

    Args:
        request: The HTTP request object.
        security_id: The ID of the security.

    Returns:
        dict: Dictionary containing transaction data for the security.
    """
    # Implement logic to fetch and return recent transactions data
    pass
