*[33m-[m[33m.[m   [33m971a1a3[m[33m ([m[1;35mrefs/stash[m[33m)[m On main: All local changes including untracked files before merge
[31m|[m[32m\[m [33m\[m  
[31m|[m [32m|[m * [33m988c4f0[m untracked files on main: 4b4ce6b Update .gitignore and database file
[31m|[m * [33md603439[m index on main: 4b4ce6b Update .gitignore and database file
[31m|[m[31m/[m  
* [33m4b4ce6b[m[33m ([m[1;36mHEAD -> [m[1;32mmain[m[33m)[m Update .gitignore and database file
* [33m0aa02d3[m[33m ([m[1;31morigin/main[m[33m)[m Add comprehensive README.md
[33m|[m * [33ma41b854[m[33m ([m[1;31morigin/feature/tinkoff-import[m[33m, [m[1;32mfeature/tinkoff-import[m[33m)[m Add initial documentation and rules for portfolio management application
[33m|[m * [33m883759e[m Updated .gitignore to include new virtual environment directory. Refactored SecurityDetailPage.vue to improve data display by changing 'security.type' to 'security.instrument_type' and transitioning performance metrics to a table format for better readability. Enhanced data fetching logic to ensure the effective current date is always up-to-date. Added a management command to fetch and cache bond coupon schedules, along with new migrations for bond metadata and coupon schedule management. Improved transaction date handling by converting date fields to datetime and updating related logic across various components. Added tests for bond ACI calculations and coupon schedule fetching.
[33m|[m * [33ma76abc6[m Enhanced transaction import handling in the TransactionImportDialog by adding support for total transaction counts, progress updates, and error handling. Improved user feedback during the import process with detailed messages for transaction statuses. Refactored the TransactionsPage and SecurityDetailPage to utilize a new TransactionRow component for better code organization and maintainability. Updated the PricesPage to comment out unused components and adjusted the FX import logic for better clarity. Additionally, updated the requirements for yfinance to the latest version for improved functionality.
[33m|[m * [33m97ecf81[m Enhanced bond transaction handling by introducing effective price calculations for bond transactions, ensuring accurate cash flow assessments. Updated the TransactionFormDialog to include bond-specific hints and suffixes, and improved the TransactionsPage to handle FX transactions more robustly. Refactored various utility functions to support bond notional calculations and integrated T-Bank API for fetching bond redemption history. Improved logging for bond-related operations and refined transaction processing logic for better accuracy.
[33m|[m * [33m772dcba[m Enhanced bond support in the portfolio management system by implementing comprehensive tracking for amortizing bonds, including new transaction types for bond redemptions and maturities. Added bond metadata management, automatic notional history creation, and improved integration with T-Bank API for accurate bond data retrieval. Updated frontend forms to display bond-specific fields and ensure proper validation. Enhanced logging for bond-related transactions and refined transaction processing logic to accommodate new bond features.
