# Generated by Django 5.0.1 on 2024-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='NAV_barchart_default_breakdown',
            field=models.CharField(blank=True, choices=[('Broker', 'Broker'), ('Asset type', 'Asset type'), ('Asset class', 'Asset class'), ('Currency', 'Currency'), ('No breakdown', 'No breakdown')], default='Asset type', max_length=12, null=True),
        ),
    ]
