# Generated by Django 5.0.1 on 2024-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='use_default_currency_where_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
