# Generated by Django 5.0.1 on 2024-06-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_use_default_currency_where_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_broker',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
