# Generated by Django 5.0.1 on 2024-06-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_custom_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_broker',
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_brokers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
