# Generated by Django 5.0.1 on 2024-11-07 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveBrokersApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.BinaryField(help_text='Encrypted API token')),
                ('key_part', models.BinaryField(help_text='User-specific part of encryption key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('account_id', models.CharField(help_text='IB Account ID associated with this token', max_length=50)),
                ('paper_trading', models.BooleanField(default=False, help_text='Whether this token is for paper trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interactive Brokers API Token',
                'verbose_name_plural': 'Interactive Brokers API Tokens',
                'unique_together': {('user', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='TinkoffApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.BinaryField(help_text='Encrypted API token')),
                ('key_part', models.BinaryField(help_text='User-specific part of encryption key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('token_type', models.CharField(choices=[('read_only', 'Read Only'), ('full_access', 'Full Access')], default='read_only', max_length=20)),
                ('sandbox_mode', models.BooleanField(default=False, help_text='Whether this token is for sandbox environment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tinkoff API Token',
                'verbose_name_plural': 'Tinkoff API Tokens',
                'unique_together': {('user', 'token_type', 'sandbox_mode')},
            },
        ),
    ]
