# Generated by Django 5.0.1 on 2024-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_remove_annualperformance_broker_and_more'),
        ('users', '0013_tinkoffapitoken_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tinkoffapitoken',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='brokergroup',
            name='brokers',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='custom_brokers',
        ),
        migrations.AddField(
            model_name='brokergroup',
            name='broker_accounts',
            field=models.ManyToManyField(related_name='groups', to='common.brokeraccounts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_broker_accounts',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tinkoffapitoken',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='tinkoffapitoken',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'token_type', 'sandbox_mode'), name='unique_active_token'),
        ),
    ]
