# Generated by Django 5.0.1 on 2024-11-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0015_accountgroup_delete_brokergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_broker_accounts',
        ),
        migrations.AddField(
            model_name='customuser',
            name='selected_account_id',
            field=models.IntegerField(blank=True, help_text="ID of the selected account, group, or broker (null for 'all')", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='selected_account_type',
            field=models.CharField(choices=[('account', 'Individual Account'), ('group', 'Account Group'), ('broker', 'Broker'), ('all', 'All Accounts')], default='all', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('selected_account_id__isnull', True), ('selected_account_type', 'all')), models.Q(models.Q(('selected_account_type', 'all'), _negated=True), ('selected_account_id__isnull', False)), _connector='OR'), name='valid_account_selection'),
        ),
    ]
