# Generated by Django 5.0.1 on 2024-05-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_assets_investor_brokers_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokers',
            name='securities',
            field=models.ManyToManyField(related_name='brokers', to='common.assets'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='assets',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Bond', 'Bond'), ('ETF', 'ETF'), ('Mutual fund', 'Mutual fund'), ('Option', 'Option'), ('Future', 'Future')], max_length=15),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽')], default='USD', max_length=3),
        ),
    ]
