# Generated by Django 5.0.1 on 2024-07-02 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_assets_restricted_alter_assets_exposure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽')], max_length=3)),
                ('bop_nav', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_out', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=20)),
                ('capital_distribution', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fx', models.DecimalField(decimal_places=2, max_digits=20)),
                ('eop_nav', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tsr', models.DecimalField(decimal_places=6, max_digits=10)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.brokers')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('investor', 'broker', 'year', 'currency')},
            },
        ),
    ]
