# Generated by Django 5.0.1 on 2024-07-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_annualperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualperformance',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
