# Generated by Django 5.0.1 on 2024-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_annualperformance_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualperformance',
            name='restricted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
