# Generated by Django 5.0.1 on 2024-07-08 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_annualperformance_broker_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualperformance',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.brokers'),
        ),
    ]
