# Generated by Django 5.0.1 on 2024-07-08 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_alter_annualperformance_broker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annualperformance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='annualperformance',
            constraint=models.UniqueConstraint(condition=models.Q(('broker__isnull', False)), fields=('investor', 'year', 'currency'), name='unique_investor_broker_year_currency'),
        ),
        migrations.AddConstraint(
            model_name='annualperformance',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_group__isnull', False)), fields=('investor', 'year', 'currency'), name='unique_investor_broker_group_year_currency'),
        ),
    ]
