# Generated by Django 5.0.1 on 2024-07-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_remove_annualperformance_unique_investor_broker_year_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokers',
            name='restricted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
