# Generated by Django 5.0.1 on 2024-07-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_brokers_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokers',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
