# Generated by Django 5.0.1 on 2024-07-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_alter_brokers_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
