# Generated by Django 5.0.1 on 2024-07-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_alter_transactions_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
