# Generated by Django 5.0.1 on 2024-08-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_alter_fxtransaction_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokers',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
