# Generated by Django 5.0.1 on 2024-08-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_alter_brokers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualperformance',
            name='tsr',
            field=models.CharField(max_length=10),
        ),
    ]
