# Generated by Django 5.0.1 on 2024-08-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_alter_annualperformance_tsr'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='update_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualperformance',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', '₣')], max_length=3),
        ),
        migrations.AlterField(
            model_name='assets',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', '₣')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='fxtransaction',
            name='from_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', '₣')], max_length=3),
        ),
        migrations.AlterField(
            model_name='fxtransaction',
            name='to_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', '₣')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', '₣')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Cash in', 'Cash in'), ('Cash out', 'Cash out'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Dividend', 'Dividend'), ('Broker commission', 'Broker commission'), ('Tax', 'Tax'), ('Interest income', 'Interest income')], max_length=30),
        ),
    ]
