# Generated by Django 5.0.1 on 2024-08-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_assets_data_source_assets_yahoo_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='data_source',
            field=models.CharField(choices=[('FT', 'Financial Times'), ('YAHOO', 'Yahoo Finance')], max_length=10),
        ),
    ]
