# Generated by Django 5.0.1 on 2024-08-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_alter_assets_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='data_source',
            field=models.CharField(blank=True, choices=[('FT', 'Financial Times'), ('YAHOO', 'Yahoo Finance')], max_length=10, null=True),
        ),
    ]
