# Generated by Django 5.0.1 on 2024-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_alter_fx_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fx',
            name='date',
            field=models.DateField(),
        ),
    ]
