# Generated by Django 5.0.1 on 2024-10-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0047_assets_fund_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
