# Generated by Django 5.0.1 on 2024-11-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_alter_assets_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='secid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='data_source',
            field=models.CharField(blank=True, choices=[('', 'None'), ('FT', 'Financial Times'), ('YAHOO', 'Yahoo Finance'), ('MICEX', 'MICEX')], max_length=10, null=True),
        ),
    ]
