# Generated by Django 5.0.1 on 2024-11-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_alter_brokers_options_remove_brokeraccounts_investor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brokers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
