# Generated by Django 5.0.1 on 2024-11-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_alter_brokers_created_at_alter_brokers_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokeraccounts',
            name='securities',
        ),
    ]
