# Generated by Django 5.0.1 on 2024-11-11 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0058_update_annual_performance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annualperformance',
            name='unique_annual_performance',
        ),
        migrations.RemoveConstraint(
            model_name='annualperformance',
            name='valid_annual_performance_selection',
        ),
        migrations.RenameField(
            model_name='annualperformance',
            old_name='selection_id',
            new_name='account_id',
        ),
        migrations.RemoveField(
            model_name='annualperformance',
            name='selection_type',
        ),
        migrations.AddField(
            model_name='annualperformance',
            name='account_type',
            field=models.CharField(choices=[('all', 'All Accounts'), ('account', 'Individual Account'), ('group', 'Account Group'), ('broker', 'Broker')], default='all', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='annualperformance',
            constraint=models.UniqueConstraint(fields=('investor', 'year', 'currency', 'restricted', 'account_type', 'account_id'), name='unique_annual_performance'),
        ),
        migrations.AddConstraint(
            model_name='annualperformance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('account_id__isnull', True), ('account_type', 'all')), models.Q(models.Q(('account_type', 'all'), _negated=True), ('account_id__isnull', False)), _connector='OR'), name='valid_annual_performance_selection'),
        ),
    ]
