# Generated by Django 5.0.1 on 2024-11-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_remove_annualperformance_unique_annual_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccounts',
            name='native_id',
            field=models.CharField(blank=True, help_text="Native account ID from broker's system", max_length=100, null=True),
        ),
    ]
