# Generated by Django 5.0.1 on 2025-10-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0065_add_bond_support_and_derivatives"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondmetadata",
            name="asset",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_metadata",
                to="common.assets",
            ),
        ),
        migrations.AlterField(
            model_name="futuremetadata",
            name="asset",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_metadata",
                to="common.assets",
            ),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="commission",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="exchange_rate",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="from_amount",
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="to_amount",
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name="optionmetadata",
            name="asset",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_metadata",
                to="common.assets",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="commission",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="quantity",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="type",
            field=models.CharField(
                choices=[
                    ("Cash in", "Cash in"),
                    ("Cash out", "Cash out"),
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
                    ("Dividend", "Dividend"),
                    ("Coupon", "Coupon"),
                    ("Broker commission", "Broker commission"),
                    ("Tax", "Tax"),
                    ("Interest income", "Interest income"),
                    ("Repo", "Repo"),
                    ("Bond redemption", "Bond redemption"),
                    ("Bond maturity", "Bond maturity"),
                ],
                max_length=30,
            ),
        ),
    ]
