# Generated by Django 5.0.1 on 2025-10-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0066_increase_decimal_precision_to_9"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="notional",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Notional/par value per bond at transaction time (for bonds only)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="exposure",
            field=models.TextField(
                choices=[
                    ("Equity", "Equity"),
                    ("FI", "Fixed income"),
                    ("FX", "Forex"),
                    ("Commodity", "Commodity"),
                    ("Derivatives", "Derivatives"),
                ],
                default="Equity",
            ),
        ),
    ]
