# Generated by Django 5.0.1 on 2025-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0078_fix_bondcouponschedule_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fxtransaction",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
