# Generated by Django 5.0.1 on 2025-10-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0061_rename_brokeraccounts_accounts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assets",
            name="tbank_instrument_uid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="annualperformance",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "$"),
                    ("EUR", "€"),
                    ("GBP", "£"),
                    ("RUB", "₽"),
                    ("CHF", "Fr"),
                    ("CNY", "¥"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "$"),
                    ("EUR", "€"),
                    ("GBP", "£"),
                    ("RUB", "₽"),
                    ("CHF", "Fr"),
                    ("CNY", "¥"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="data_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("FT", "Financial Times"),
                    ("YAHOO", "Yahoo Finance"),
                    ("MICEX", "MICEX"),
                    ("TBANK", "T-Bank"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="commission_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "$"),
                    ("EUR", "€"),
                    ("GBP", "£"),
                    ("RUB", "₽"),
                    ("CHF", "Fr"),
                    ("CNY", "¥"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="from_currency",
            field=models.CharField(
                choices=[
                    ("USD", "$"),
                    ("EUR", "€"),
                    ("GBP", "£"),
                    ("RUB", "₽"),
                    ("CHF", "Fr"),
                    ("CNY", "¥"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="to_currency",
            field=models.CharField(
                choices=[
                    ("USD", "$"),
                    ("EUR", "€"),
                    ("GBP", "£"),
                    ("RUB", "₽"),
                    ("CHF", "Fr"),
                    ("CNY", "¥"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "$"),
                    ("EUR", "€"),
                    ("GBP", "£"),
                    ("RUB", "₽"),
                    ("CHF", "Fr"),
                    ("CNY", "¥"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="type",
            field=models.CharField(
                choices=[
                    ("Cash in", "Cash in"),
                    ("Cash out", "Cash out"),
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
                    ("Dividend", "Dividend"),
                    ("Coupon", "Coupon"),
                    ("Broker commission", "Broker commission"),
                    ("Tax", "Tax"),
                    ("Interest income", "Interest income"),
                    ("Repo", "Repo"),
                ],
                max_length=30,
            ),
        ),
    ]
