# Generated by Django 5.0.1 on 2025-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0062_add_tbank_instrument_uid_to_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="aci",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
