# Generated by Django 5.0.1 on 2025-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0063_add_aci_to_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True),
        ),
    ]
