# Generated by Django 5.0.1 on 2025-10-04 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0067_add_notional_to_transactions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notionalhistory",
            name="unique_notional_change",
        ),
    ]
