# Generated by Django 5.0.1 on 2025-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0068_remove_notional_history_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="fx",
            name="RUBCNY",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
