# Generated by Django 5.0.1 on 2025-10-05 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0069_add_RUBCNY_pair"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fx",
            old_name="RUBCNY",
            new_name="CNYUSD",
        ),
    ]
