# Generated by Django 5.0.1 on 2025-10-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0070_replace_RUBCNY_with_CNYUSD"),
    ]

    operations = [
        migrations.AddField(
            model_name="assets",
            name="ticker",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
