# Generated by Django 5.0.1 on 2025-10-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0071_add_ticker_field_to_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fxtransaction",
            name="from_amount",
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="to_amount",
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
    ]
