# Generated by Django 5.0.1 on 2025-10-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0072_alter_fx_amounts_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=25, null=True
            ),
        ),
    ]
