# Generated by Django 5.0.1 on 2025-10-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0073_alter_transaction_amounts_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="aci",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
