# Generated by Django 5.0.1 on 2025-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0074_alter_aci_amounts_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondmetadata",
            name="nominal_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "$"),
                    ("EUR", "€"),
                    ("GBP", "£"),
                    ("RUB", "₽"),
                    ("CHF", "Fr"),
                    ("CNY", "¥"),
                ],
                help_text="Currency in which the nominal/face value is denominated",
                max_length=3,
                null=True,
            ),
        ),
    ]
