# Generated by Django 5.0.1 on 2025-10-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0075_add_nominal_currency_to_bondmetadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BondCouponSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_number",
                    models.IntegerField(help_text="Sequential coupon number"),
                ),
                (
                    "coupon_start_date",
                    models.DateField(help_text="Start date of the coupon period"),
                ),
                (
                    "coupon_end_date",
                    models.DateField(
                        help_text="End date of the coupon period (accrual cutoff)"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(help_text="Actual payment date for the coupon"),
                ),
                (
                    "coupon_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Coupon rate for this period (for floating rate bonds)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "coupon_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coupon payment amount per bond in nominal currency",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        blank=True,
                        help_text="Coupon type (FIXED, FLOATING, etc.)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this schedule was last fetched from API",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_schedule",
                        to="common.assets",
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "coupon_number"],
                "indexes": [
                    models.Index(
                        fields=["asset", "coupon_end_date"],
                        name="common_bond_asset_i_729fca_idx",
                    ),
                    models.Index(
                        fields=["asset", "payment_date"],
                        name="common_bond_asset_i_9a2ea9_idx",
                    ),
                ],
                "unique_together": {("asset", "coupon_number")},
            },
        ),
    ]
