# Generated by Django 5.0.1 on 2025-10-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0076_add_bond_coupon_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bondcouponschedule",
            name="coupon_amount",
        ),
        migrations.RemoveField(
            model_name="bondcouponschedule",
            name="coupon_rate",
        ),
        migrations.AddField(
            model_name="bondcouponschedule",
            name="coupon_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "$"),
                    ("EUR", "€"),
                    ("GBP", "£"),
                    ("RUB", "₽"),
                    ("CHF", "Fr"),
                    ("CNY", "¥"),
                ],
                help_text="Currency of the coupon payment",
                max_length=3,
                null=True,
            ),
        ),
    ]
