# Generated by Django 5.0.1 on 2025-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0077_add_coupon_currency_to_bondcouponschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondcouponschedule",
            name="coupon_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coupon payment amount per bond in nominal currency",
                max_digits=15,
                null=True,
            ),
        ),
    ]
