# Generated by Django 5.2.6 on 2025-10-12 16:08

from django.db import migrations

import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0080_update_existing_dates_to_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="created_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="updated_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bondcouponschedule",
            name="last_updated",
            field=common.fields.TimezoneAwareDateTimeField(
                auto_now=True, help_text="When this schedule was last fetched from API"
            ),
        ),
        migrations.AlterField(
            model_name="bondmetadata",
            name="created_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bondmetadata",
            name="updated_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="brokers",
            name="created_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="brokers",
            name="updated_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="futuremetadata",
            name="created_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="futuremetadata",
            name="updated_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="date",
            field=common.fields.TimezoneAwareDateTimeField(),
        ),
        migrations.AlterField(
            model_name="optionmetadata",
            name="created_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="optionmetadata",
            name="updated_at",
            field=common.fields.TimezoneAwareDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=common.fields.TimezoneAwareDateTimeField(db_index=True),
        ),
    ]
