# Generated by Django 5.2.6 on 2025-10-12 16:10

from django.db import migrations

import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0081_update_to_timezone_aware_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondcouponschedule",
            name="coupon_end_date",
            field=common.fields.TimezoneAwareDateField(
                help_text="End date of the coupon period (accrual cutoff)"
            ),
        ),
        migrations.AlterField(
            model_name="bondcouponschedule",
            name="coupon_start_date",
            field=common.fields.TimezoneAwareDateField(
                help_text="Start date of the coupon period"
            ),
        ),
        migrations.AlterField(
            model_name="bondcouponschedule",
            name="payment_date",
            field=common.fields.TimezoneAwareDateField(
                help_text="Actual payment date for the coupon"
            ),
        ),
        migrations.AlterField(
            model_name="bondmetadata",
            name="issue_date",
            field=common.fields.TimezoneAwareDateField(
                blank=True, help_text="Bond issue date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bondmetadata",
            name="maturity_date",
            field=common.fields.TimezoneAwareDateField(
                blank=True, help_text="Bond maturity date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="futuremetadata",
            name="expiration_date",
            field=common.fields.TimezoneAwareDateField(
                blank=True, help_text="Futures expiration date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="fx",
            name="date",
            field=common.fields.TimezoneAwareDateField(unique=True),
        ),
        migrations.AlterField(
            model_name="notionalhistory",
            name="date",
            field=common.fields.TimezoneAwareDateField(
                db_index=True, help_text="Date when the notional change occurred"
            ),
        ),
        migrations.AlterField(
            model_name="optionmetadata",
            name="expiration_date",
            field=common.fields.TimezoneAwareDateField(
                blank=True, help_text="Option expiration date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="prices",
            name="date",
            field=common.fields.TimezoneAwareDateField(),
        ),
    ]
