# Generated by Django 5.2.7 on 2025-11-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0082_update_date_fields_to_timezone_aware"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondcouponschedule",
            name="coupon_end_date",
            field=models.DateField(
                help_text="End date of the coupon period (accrual cutoff)"
            ),
        ),
        migrations.AlterField(
            model_name="bondcouponschedule",
            name="coupon_start_date",
            field=models.DateField(help_text="Start date of the coupon period"),
        ),
        migrations.AlterField(
            model_name="bondcouponschedule",
            name="payment_date",
            field=models.DateField(help_text="Actual payment date for the coupon"),
        ),
    ]
