# Generated by Django 5.2.7 on 2025-11-03 17:41

from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0083_alter_bondcouponschedule_coupon_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bondcouponschedule",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this schedule was last fetched from API"
            ),
        ),
        migrations.AlterField(
            model_name="bondmetadata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bondmetadata",
            name="issue_date",
            field=models.DateField(blank=True, help_text="Bond issue date", null=True),
        ),
        migrations.AlterField(
            model_name="bondmetadata",
            name="maturity_date",
            field=models.DateField(
                blank=True, help_text="Bond maturity date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bondmetadata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="brokers",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="brokers",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="futuremetadata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="futuremetadata",
            name="expiration_date",
            field=models.DateField(
                blank=True, help_text="Futures expiration date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="futuremetadata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fx",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="fxtransaction",
            name="date",
            field=common.fields.NaiveDateTimeField(),
        ),
        migrations.AlterField(
            model_name="notionalhistory",
            name="date",
            field=models.DateField(
                db_index=True, help_text="Date when the notional change occurred"
            ),
        ),
        migrations.AlterField(
            model_name="optionmetadata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="optionmetadata",
            name="expiration_date",
            field=models.DateField(
                blank=True, help_text="Option expiration date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="optionmetadata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="prices",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=common.fields.NaiveDateTimeField(db_index=True),
        ),
    ]
