# Generated by Django 5.2.7 on 2025-11-30 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0084_convert_to_naive_datetime_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assets",
            constraint=models.UniqueConstraint(
                fields=("ISIN", "currency"), name="unique_asset_currency_entry"
            ),
        ),
    ]
