# Generated by Django 5.2.6 on 2026-02-02 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0085_assets_unique_asset_currency_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date when the split occurred')),
                ('split_from', models.PositiveIntegerField(help_text='Number of shares before split (e.g., 1 for a 2:1 split)')),
                ('split_to', models.PositiveIntegerField(help_text='Number of shares after split (e.g., 2 for a 2:1 split)')),
                ('adjustment_factor', models.DecimalField(decimal_places=10, help_text='Price adjustment factor (split_from / split_to). Multiply historical prices by this to get post-split equivalent.', max_digits=15)),
                ('source', models.CharField(choices=[('TRANSACTION', 'From Corporate Action Transaction'), ('MANUAL', 'Manually Entered'), ('IMPORT', 'Imported from External Source')], default='MANUAL', help_text='How this split record was created', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Cash in', 'Cash in'), ('Cash out', 'Cash out'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Dividend', 'Dividend'), ('Coupon', 'Coupon'), ('Broker commission', 'Broker commission'), ('Tax', 'Tax'), ('Interest income', 'Interest income'), ('Repo', 'Repo'), ('Bond redemption', 'Bond redemption'), ('Bond maturity', 'Bond maturity'), ('Corporate Action', 'Corporate Action')], max_length=30),
        ),
        migrations.AddField(
            model_name='splithistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_history', to='common.assets'),
        ),
        migrations.AddField(
            model_name='splithistory',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Source Corporate Action transaction (if auto-created)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_history_entries', to='common.transactions'),
        ),
        migrations.AddIndex(
            model_name='splithistory',
            index=models.Index(fields=['asset', 'date'], name='common_spli_asset_i_5c5535_idx'),
        ),
    ]
