# Generated by Django 5.2.6 on 2026-02-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0086_add_split_history_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='split_from',
            field=models.PositiveIntegerField(blank=True, help_text='Number of shares before split (e.g., 1 for a 2:1 split)', null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='split_to',
            field=models.PositiveIntegerField(blank=True, help_text='Number of shares after split (e.g., 2 for a 2:1 split)', null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Cash in', 'Cash in'), ('Cash out', 'Cash out'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Dividend', 'Dividend'), ('Coupon', 'Coupon'), ('Broker commission', 'Broker commission'), ('Tax', 'Tax'), ('Interest income', 'Interest income'), ('Repo', 'Repo'), ('Bond redemption', 'Bond redemption'), ('Bond maturity', 'Bond maturity'), ('Stock split', 'Stock split')], max_length=30),
        ),
    ]
