# Generated by Django 6.0.4 on 2026-04-15 18:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0087_add_split_fields_to_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Cash in', 'Cash in'), ('Cash out', 'Cash out'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Dividend', 'Dividend'), ('Coupon', 'Coupon'), ('Broker commission', 'Broker commission'), ('Tax', 'Tax'), ('Interest income', 'Interest income'), ('Repo', 'Repo'), ('Bond redemption', 'Bond redemption'), ('Bond maturity', 'Bond maturity'), ('Stock split', 'Stock split'), ('Merger out', 'Merger out'), ('Merger in', 'Merger in')], max_length=30),
        ),
        migrations.CreateModel(
            name='MergerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merger_date', models.DateField(help_text='Date when the merger took effect')),
                ('conversion_ratio', models.DecimalField(blank=True, decimal_places=9, help_text='New shares per old share (e.g. 0.75 means 1 old → 0.75 new)', max_digits=18, null=True)),
                ('cash_per_share', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Cash received per old share (for all-cash or hybrid)', max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merger_records', to=settings.AUTH_USER_MODEL)),
                ('new_security', models.ForeignKey(blank=True, help_text='New security (null for all-cash mergers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mergers_in', to='common.assets')),
                ('old_security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mergers_out', to='common.assets')),
            ],
            options={
                'ordering': ['-merger_date'],
            },
        ),
        migrations.AddField(
            model_name='transactions',
            name='merger',
            field=models.ForeignKey(blank=True, help_text='Linked merger record (for Merger in/out transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='common.mergerrecord'),
        ),
    ]
