# Generated by Django 6.0.4 on 2026-06-07 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0088_alter_transactions_type_mergerrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fxtransaction',
            name='import_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fxtransaction',
            name='import_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fxtransaction',
            name='import_event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fxtransaction',
            name='import_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fxtransaction',
            name='import_provider',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='import_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='import_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='import_event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='import_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='import_provider',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Bond', 'Bond'), ('ETF', 'ETF'), ('Mutual fund', 'Mutual fund'), ('Option', 'Option'), ('Future', 'Future'), ('Crypto', 'Crypto')], max_length=15),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Cash in', 'Cash in'), ('Cash out', 'Cash out'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Dividend', 'Dividend'), ('Coupon', 'Coupon'), ('Broker commission', 'Broker commission'), ('Tax', 'Tax'), ('Interest income', 'Interest income'), ('Repo', 'Repo'), ('Bond redemption', 'Bond redemption'), ('Bond maturity', 'Bond maturity'), ('Stock split', 'Stock split'), ('Merger out', 'Merger out'), ('Merger in', 'Merger in'), ('Crypto reward', 'Crypto reward'), ('Crypto transfer in', 'Crypto transfer in'), ('Crypto transfer out', 'Crypto transfer out'), ('Crypto trade in', 'Crypto trade in'), ('Crypto trade out', 'Crypto trade out'), ('Option settlement', 'Option settlement')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='fxtransaction',
            constraint=models.CheckConstraint(condition=(models.Q(import_event_id__isnull=True) | models.Q(import_event_id='') | (models.Q(import_provider__isnull=False) & ~models.Q(import_provider='') & models.Q(import_account_id__isnull=False) & ~models.Q(import_account_id=''))), name='fx_transaction_import_event_requires_provider_account'),
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.CheckConstraint(condition=(models.Q(import_event_id__isnull=True) | models.Q(import_event_id='') | (models.Q(import_provider__isnull=False) & ~models.Q(import_provider='') & models.Q(import_account_id__isnull=False) & ~models.Q(import_account_id=''))), name='transaction_import_event_requires_provider_account'),
        ),
        migrations.AddConstraint(
            model_name='fxtransaction',
            constraint=models.UniqueConstraint(condition=(models.Q(import_event_id__isnull=False) & ~models.Q(import_event_id='')), fields=('investor', 'account', 'import_provider', 'import_account_id', 'import_event_id'), name='unique_fx_transaction_provider_event'),
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.UniqueConstraint(condition=(models.Q(import_event_id__isnull=False) & ~models.Q(import_event_id='')), fields=('investor', 'account', 'import_provider', 'import_account_id', 'import_event_id'), name='unique_transaction_provider_event'),
        ),
    ]
