# Generated by Django 6.0.7 on 2026-07-29 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0089_crypto_exchange_import_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fx',
            name='from_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fx',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fx',
            name='to_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fx',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='fx',
            constraint=models.UniqueConstraint(fields=('date', 'from_currency', 'to_currency'), name='unique_fx_date_pair'),
        ),
    ]
