# Generated by Django 6.0.7 on 2026-07-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0091_fx_migrate_wide_to_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fx',
            name='CHFGBP',
        ),
        migrations.RemoveField(
            model_name='fx',
            name='CNYUSD',
        ),
        migrations.RemoveField(
            model_name='fx',
            name='PLNUSD',
        ),
        migrations.RemoveField(
            model_name='fx',
            name='RUBUSD',
        ),
        migrations.RemoveField(
            model_name='fx',
            name='USDEUR',
        ),
        migrations.RemoveField(
            model_name='fx',
            name='USDGBP',
        ),
    ]
