# Generated by Django 6.0.7 on 2026-07-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0093_seed_stablecoin_fx_peg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', 'Fr'), ('CNY', '¥'), ('USDT', '₮'), ('USDC', '$')], default='USD', max_length=4),
        ),
        migrations.AlterField(
            model_name='fxtransaction',
            name='commission_currency',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', 'Fr'), ('CNY', '¥'), ('USDT', '₮'), ('USDC', '$')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='fxtransaction',
            name='from_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', 'Fr'), ('CNY', '¥'), ('USDT', '₮'), ('USDC', '$')], max_length=4),
        ),
        migrations.AlterField(
            model_name='fxtransaction',
            name='to_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', 'Fr'), ('CNY', '¥'), ('USDT', '₮'), ('USDC', '$')], max_length=4),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', 'Fr'), ('CNY', '¥'), ('USDT', '₮'), ('USDC', '$')], default='USD', max_length=4),
        ),
    ]
