# Generated by Django 6.0.7 on 2026-08-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0095_migrate_stablecoins_to_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='commission_currency',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', 'Fr'), ('CNY', '¥'), ('USDT', '₮'), ('USDC', '$')], max_length=4, null=True),
        ),
    ]
