# Generated by Django 6.0.7 on 2026-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0096_transactions_commission_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cash_flow',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=16, null=True),
        ),
    ]
