# Generated by Django 6.0.7 on 2026-08-04 18:56

import django.core.validators
from django.db import migrations, models


def set_crypto_broker_cash_precision(apps, schema_editor):
    """Set cash_precision=8 for known crypto brokers (OKX, Bybit)."""
    Brokers = apps.get_model("common", "Brokers")
    for name in ["OKX", "Bybit"]:
        updated = Brokers.objects.filter(name__icontains=name).update(cash_precision=8)
        if updated:
            print(f"  Set cash_precision=8 for {updated} '{name}' broker(s)")


def revert_crypto_broker_cash_precision(apps, schema_editor):
    """Revert crypto brokers to default=2."""
    Brokers = apps.get_model("common", "Brokers")
    for name in ["OKX", "Bybit"]:
        Brokers.objects.filter(name__icontains=name).update(cash_precision=2)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0097_alter_transactions_cash_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokers',
            name='cash_precision',
            field=models.IntegerField(default=2, help_text='Decimal places the broker uses for cash settlement (e.g. 2 for traditional, 8 for crypto).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.RunPython(set_crypto_broker_cash_precision, revert_crypto_broker_cash_precision),
    ]
