# Generated by Django 6.0.7 on 2026-08-04 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0097_alter_transactions_cash_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokers',
            name='cash_precision',
            field=models.IntegerField(default=2, help_text='Decimal places the broker uses for cash settlement (e.g. 2 for traditional, 8 for crypto).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
