# Generated by Django 6.0.7 on 2026-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0099_backfill_crypto_yahoo_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="type",
            field=models.CharField(
                choices=[
                    ("Cash in", "Cash in"),
                    ("Cash out", "Cash out"),
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
                    ("Dividend", "Dividend"),
                    ("Coupon", "Coupon"),
                    ("Broker commission", "Broker commission"),
                    ("Tax", "Tax"),
                    ("Interest income", "Interest income"),
                    ("Repo", "Repo"),
                    ("Bond redemption", "Bond redemption"),
                    ("Bond maturity", "Bond maturity"),
                    ("Stock split", "Stock split"),
                    ("Merger out", "Merger out"),
                    ("Merger in", "Merger in"),
                    ("Crypto reward", "Crypto reward"),
                    ("Crypto transfer in", "Crypto transfer in"),
                    ("Crypto transfer out", "Crypto transfer out"),
                    ("Crypto trade in", "Crypto trade in"),
                    ("Crypto trade out", "Crypto trade out"),
                    ("Crypto commission", "Crypto commission"),
                    ("Option settlement", "Option settlement"),
                ],
                max_length=30,
            ),
        ),
    ]
