# Generated by Django 5.0.1 on 2025-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_remove_tinkoffapitoken_unique_active_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="default_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "$"),
                    ("EUR", "€"),
                    ("GBP", "£"),
                    ("RUB", "₽"),
                    ("CHF", "Fr"),
                    ("CNY", "¥"),
                ],
                default="USD",
                max_length=3,
                null=True,
            ),
        ),
    ]
