# Generated by Django 5.2.7 on 2025-11-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_customuser_default_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="selected_account_type",
            field=models.CharField(
                choices=[
                    ("all", "All Accounts"),
                    ("account", "Individual Account"),
                    ("group", "Account Group"),
                    ("broker", "Broker"),
                ],
                default="all",
                max_length=50,
            ),
        ),
    ]
