# Generated by Django 6.0.4 on 2026-06-08 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0089_crypto_exchange_import_metadata'),
        ('users', '0020_alter_customuser_selected_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BybitApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=120)),
                ('testnet', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bybit_tokens', to='common.brokers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bybit API Token',
                'verbose_name_plural': 'Bybit API Tokens',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'broker', 'testnet'), name='unique_active_bybit_token')],
            },
        ),
        migrations.CreateModel(
            name='OKXApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=120)),
                ('encrypted_passphrase', models.BinaryField()),
                ('simulated_trading', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okx_tokens', to='common.brokers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OKX API Token',
                'verbose_name_plural': 'OKX API Tokens',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'broker', 'simulated_trading'), name='unique_active_okx_token')],
            },
        ),
    ]
