# Generated by Django 6.0.7 on 2026-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_bybit_okx_api_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="bybitapitoken",
            name="key_version",
            field=models.IntegerField(default=1, help_text="Encryption key version"),
        ),
        migrations.AddField(
            model_name="interactivebrokersapitoken",
            name="key_version",
            field=models.IntegerField(default=1, help_text="Encryption key version"),
        ),
        migrations.AddField(
            model_name="okxapitoken",
            name="key_version",
            field=models.IntegerField(default=1, help_text="Encryption key version"),
        ),
        migrations.AddField(
            model_name="tinkoffapitoken",
            name="key_version",
            field=models.IntegerField(default=1, help_text="Encryption key version"),
        ),
    ]
