# Generated by Django 6.0.7 on 2026-07-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_bybitapitoken_key_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_currency',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽'), ('CHF', 'Fr'), ('CNY', '¥'), ('USDT', '₮'), ('USDC', '$')], default='USD', max_length=4, null=True),
        ),
    ]
