# Generated by Django 6.0.7 on 2026-08-03 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_stablecoin_currency_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='digits',
            field=models.IntegerField(default=0, error_messages={'max_value': 'The value for digits must be less than or equal to 9.', 'min_value': 'The value for digits must be greater than or equal to 0.'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
